#!/usr/bin/env bun
import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";

type MockSemantics = "success" | "needs_retry" | "handoff" | "abandoned";

interface Args {
  mockSemantics: MockSemantics;
  mockSkipComplete: boolean;
  mockSleep: number | undefined;
  mockFailFetch: boolean;
  clean: boolean;
  dryRun: boolean;
  keepAlive: boolean;
  timeoutSec: number;
}

function parseArgs(argv: string[]): Args {
  const args: Args = {
    mockSemantics: "success",
    mockSkipComplete: false,
    mockSleep: undefined,
    mockFailFetch: false,
    clean: false,
    dryRun: false,
    keepAlive: false,
    timeoutSec: 30,
  };

  for (const raw of argv) {
    if (raw === "--mock-skip-complete") args.mockSkipComplete = true;
    else if (raw === "--mock-fail-fetch") args.mockFailFetch = true;
    else if (raw === "--clean") args.clean = true;
    else if (raw === "--dry-run") args.dryRun = true;
    else if (raw === "--keep-alive") args.keepAlive = true;
    else if (raw.startsWith("--mock-semantics=")) {
      const v = raw.slice("--mock-semantics=".length) as MockSemantics;
      if (!(["success", "needs_retry", "handoff", "abandoned"] as const).includes(v)) {
        throw new Error(`Invalid --mock-semantics: ${v}`);
      }
      args.mockSemantics = v;
    } else if (raw.startsWith("--mock-sleep=")) {
      const v = Number(raw.slice("--mock-sleep=".length));
      if (!Number.isFinite(v) || v < 0) throw new Error(`Invalid --mock-sleep: ${raw}`);
      args.mockSleep = v;
    } else if (raw.startsWith("--timeout=")) {
      const v = Number(raw.slice("--timeout=".length));
      if (!Number.isFinite(v) || v <= 0) throw new Error(`Invalid --timeout: ${raw}`);
      args.timeoutSec = v;
    } else {
      throw new Error(`Unknown arg: ${raw}`);
    }
  }
  return args;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function mkdirp(dir: string): Promise<void> {
  await fs.mkdir(dir, { recursive: true });
}

async function rmrf(dir: string): Promise<void> {
  await fs.rm(dir, { recursive: true, force: true });
}

async function fetchJson(url: string, init?: RequestInit): Promise<any> {
  const res = await fetch(url, init);
  const text = await res.text();
  if (!res.ok) throw new Error(`HTTP ${res.status} ${res.statusText}: ${text}`);
  try {
    return JSON.parse(text);
  } catch {
    return text;
  }
}

async function waitFor(fn: () => Promise<boolean>, timeoutMs: number, tickMs = 250): Promise<void> {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    if (await fn()) return;
    await sleep(tickMs);
  }
  throw new Error(`Timed out after ${timeoutMs}ms`);
}

function nowIso(): string {
  return new Date().toISOString();
}

function buildWorkflowMd(mockAgentAbsPath: string, mockEnv: Record<string, string>): string {
  const lines = [
    "---",
    "tracker:",
    "  type: e2e",
    "agent:",
    `  binary: \"${mockAgentAbsPath.replace(/\\/g, "\\\\")}\"`,
    "  timeout_ms: 10000",
    "  max_retries: 0",
  ];

  // S3: Mock env vars must go through agent.extra_env in the workflow YAML.
  // The spawner's ENV_ALLOWLIST strips them from the server env before they
  // reach child processes, so direct env passthrough does not work.
  if (Object.keys(mockEnv).length > 0) {
    lines.push("  extra_env:");
    for (const [k, v] of Object.entries(mockEnv)) {
      lines.push(`    ${k}: "${v}"`);
    }
  }

  lines.push(
    "---",
    "",
    "# nano-symphony e2e WORKFLOW",
    "",
    "This file is generated by scripts/e2e-debug.ts.",
    "",
    "{{ issue.title }}\n\nAttempt: {{ attempt }}\n\n{{ issue.description }}",
    ""
  );

  return lines.join("\n");
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const repoRoot = process.cwd();

  const e2eRoot = path.join(repoRoot, ".e2e");
  const dbPath = path.join(e2eRoot, "symphony.db");
  const workspacesRoot = path.join(e2eRoot, "workspaces");
  const workflowPath = path.join(e2eRoot, "WORKFLOW.md");
  const mockAgentPath = path.join(repoRoot, "scripts", "mock-agent.sh");
  const port = 4199;
  const baseUrl = `http://localhost:${port}`;

  if (args.clean) await rmrf(e2eRoot);
  await mkdirp(e2eRoot);
  await mkdirp(workspacesRoot);

  // Build mock env vars to pass through agent.extra_env in the workflow YAML.
  // S3: the spawner's ENV_ALLOWLIST strips MOCK_* vars from the server env before
  // they reach the mock agent, so they must travel via the workflow config instead.
  const mockEnv: Record<string, string> = {
    MOCK_SEMANTICS: args.mockSemantics,
  };
  if (args.mockSkipComplete) mockEnv.MOCK_SKIP_COMPLETE = "1";
  if (args.mockFailFetch) mockEnv.MOCK_FAIL_FETCH = "1";
  if (args.mockSleep != null) mockEnv.MOCK_SLEEP_BEFORE_COMPLETE = String(args.mockSleep);

  await fs.writeFile(path.join(e2eRoot, "WORKFLOW.md"), buildWorkflowMd(mockAgentPath, mockEnv), "utf-8");
  await fs.writeFile(
    path.join(e2eRoot, "README.txt"),
    [
      `Generated at: ${nowIso()}`,
      `DB_PATH=${dbPath}`,
      `WORKSPACE_ROOT=${workspacesRoot}`,
      `WORKFLOW_PATH=${workflowPath}`,
      `PORT=${port}`,
      "",
      "To clean: rm -rf .e2e",
      "",
    ].join("\n"),
    "utf-8"
  );

  // W3: Inject a stable API_TOKEN so all requests are authenticated.
  // Without this, every API call returns 401 and the e2e test hangs on the
  // readiness poll until it times out.
  const e2eToken = process.env.API_TOKEN ?? "e2e-debug-token-local";
  const env: Record<string, string> = {
    ...process.env,
    PORT: String(port),
    DB_PATH: dbPath,
    WORKSPACE_ROOT: workspacesRoot,
    WORKFLOW_PATH: workflowPath,
    NANO_BIN: mockAgentPath,
    API_TOKEN: e2eToken,
  };

  // Helper that injects the auth header on every fetch
  const authHeaders = { "X-Symphony-Token": e2eToken };

  const server = Bun.spawn(["bun", "src/index.ts"], {
    env,
    stdout: "inherit",
    stderr: "inherit",
  });

  try {
    // W3: Poll /health (auth-exempt) for readiness instead of /issues (auth-required)
    // to avoid a 401 loop that would exhaust the timeout before the server is ready.
    await waitFor(async () => {
      try {
        const res = await fetch(`${baseUrl}/api/v1/health`);
        return res.ok;
      } catch {
        return false;
      }
    }, 10_000);

    const issue = await fetchJson(`${baseUrl}/api/v1/issues`, {
      method: "POST",
      headers: { "content-type": "application/json", ...authHeaders },
      body: JSON.stringify({
        identifier: "E2E-1",
        title: "E2E debug issue",
        description: "Created by scripts/e2e-debug.ts",
        priority: "medium",
        state: "todo",
        labels: ["e2e"],
      }),
    });

    const issueId = issue?.id as string | undefined;
    if (!issueId) throw new Error(`Missing issue id in response: ${JSON.stringify(issue)}`);
    console.log(`[e2e] created issue id=${issueId}`);

    await waitFor(async () => {
      try {
        const run = await fetchJson(`${baseUrl}/api/v1/runs/${issueId}`, { headers: authHeaders });
        console.log(`[e2e] run discovered: ${JSON.stringify({ last_state: run.last_state, workspace_path: run.workspace_path })}`);
        return true;
      } catch {
        return false;
      }
    }, args.timeoutSec * 1000);

    if (args.dryRun) {
      console.log("[e2e] --dry-run set; not waiting for terminal state");
      return;
    }

    await waitFor(async () => {
      let run: any;
      try {
        run = await fetchJson(`${baseUrl}/api/v1/runs/${issueId}`, { headers: authHeaders });
      } catch {
        return false;
      }
      const state = String(run.last_state);
      if (["released", "in_review", "paused", "cancelled", "retry_queued"].includes(state)) {
        console.log(`[e2e] run last_state=${state}`);
        return true;
      }
      return false;
    }, args.timeoutSec * 1000);

    const runAfter = await fetchJson(`${baseUrl}/api/v1/runs/${issueId}`, { headers: authHeaders });
    console.log(`[e2e] run_snapshot=${JSON.stringify({ last_state: runAfter.last_state, last_attempt: runAfter.last_attempt, last_error: runAfter.last_error })}`);

    const events = await fetchJson(`${baseUrl}/api/v1/events`, { headers: authHeaders });
    const issueEvents = (events as any[]).filter((e) => e.issue_id === issueId);
    console.log(`[e2e] events_count=${issueEvents.length}`);
    const lastKinds = issueEvents.slice(-8).map((e) => e.kind).join(",");
    console.log(`[e2e] last_kinds=${lastKinds}`);
  } finally {
    if (args.keepAlive) {
      console.log("[e2e] --keep-alive set; server left running");
    } else {
      server.kill();
      await server.exited;
    }
  }
}

main().catch((err) => {
  console.error("[e2e] failed", err);
  process.exit(1);
});
